<a href="https://colab.research.google.com/github/ChangJooOh/AIP2/blob/master/ITP1170x_Lab0(NumPy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ITP11701 Introduction to AI Programming II, Fall 2020
Practice: NumPy arrays (September.09)

## Goals 
   In this Lab session, you practice writing Python NumPy moudle 
   Most of the statistical analysis which needs data to be stored in memory uses NumPy. 
   You will be looking into the following topics in here.

Issues covered:
  1. Why NumPy and Not Python lists
  2. How to create NumPy Arrays
  3. Create N-Dimensional Array
  4. Mathematical Operations and Array Calculations 

## 1. Why NumPy and Not Python lists
   

NumPy provides efficient storage and better ways of handling data for Mathematical Operations.

NumPy is the fundamental package for scientific computing with Python. Extremely useful!!

links used:
https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html    

## 2. How to create NumPy Arrays

 - import the "numpy" library as "np"

In [1]:
import numpy as np
print(np.__version__)

1.18.5


- using .array(....) function

In [2]:
np_arr = np.array([1,2,3,4,5,6])

In [3]:
np_arr  #  print(np_arr)

array([1, 2, 3, 4, 5, 6])

In [4]:
py_arr = [1,2,3,4,5,6]

In [5]:
py_arr

[1, 2, 3, 4, 5, 6]

- Check the difference between python array and numpy array

In [6]:
py_arr = [1,2,3,4, "Hi",5,6] #heterogenuous

In [7]:
py_arr

[1, 2, 3, 4, 'Hi', 5, 6]

In [8]:
np_arr = np.array([1,2,3, "bye",4,5,6])  #homogenous

In [9]:
np_arr

array(['1', '2', '3', 'bye', '4', '5', '6'], dtype='<U21')

 - Create a list with values 1 to 10 and assign it to the variable "list1"
 - Create an integer array from list1 and assign it
 - Check the data type of each array (use the attribute "dtype")

In [10]:
list1= range(1, 11)
np_arr = np.array(list1, dtype = np.int16)   # np_arr = np.array(list1, "i") 
print(np_arr, np_arr.dtype)

[ 1  2  3  4  5  6  7  8  9 10] int16


 - Create a list with values 1 to 10 and assign it to the variable "list1"
 - Create an array of floats from list1 and assign it
 - Check the data type of each array (use the attribute "dtype")

In [11]:
list1= range(1, 11)
np_arr = np.array(list1, dtype = np.float64)   # np_arr = np.array(list1, "i") 
print(np_arr, np_arr.dtype)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] float64


## 3. Create N-Dimensional Array

- using .array() and many other function   # create numpy array
- using .reshape() function   # reshapes the array without changing the original shape
- using .arange() function    # create sequence of numbers in array
- using .empty()              # to get a matrix of all random numbers
- using .zeros() and ones()   # numpy provides the utility to create some usual matrices which are commonly used
- using .diag()               # diagonal elements   np.diag([1,1,1,1])
- using .ravel() function 

<script src="https://npmcdn.com/jupyter-js-widgets@~1.2.0/dist/embed.js"></script><img src='https://www.oreilly.com/library/view/elegant-scipy/9781491922927/assets/elsp_0105.png'><script type="application/vnd.jupyter-embedded-widgets">{}</script>

In [12]:
import numpy as np
np_arr=np.arange(0,10,1)
np_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<script src="https://npmcdn.com/jupyter-js-widgets@~1.2.0/dist/embed.js"></script><img src='https://t1.daumcdn.net/cfile/tistory/99B4C23C5A884A392C'><script type="application/vnd.jupyter-embedded-widgets">{}</script>

In [13]:
np_arr.reshape(2, 5) #2 by 5

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
np_arr 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np_arr = np.empty((5,2))

In [16]:
np_arr

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

In [17]:
np_arr=np.empty((5,2), dtype = np.int8)

In [18]:
np_arr

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [19]:
np_arr = np.zeros((5,2)) # Create an array of all zeros

In [20]:
np_arr

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
np_arr = np.ones((5,2), dtype = np.int8)  # Create an array of all ones

In [22]:
np_arr

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [23]:
np_arr.ravel()

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [24]:
np.eye(3) # 3 by b matrics

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.full((2,2), 7)  # Create a constant array

array([[7, 7],
       [7, 7]])

In [28]:
np_arr

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

#### Practice 1
- Create an array of shape (2,3,4) of zeros
- Create an array of shape (3,4,5) of ones
- Create an array with values 0 to 49 using the np.arange() 

In [29]:
import numpy as np
np_arr=np.zeros((2,3,4))
print(np_arr)
np_arr = np.ones((3, 4, 5))
print(np_arr)
np_arr = np.arange(50)
print(np_arr)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


#### Practice  2    
- Create an array of from the list [2,5,5, -7.2, 3,5, 2.7, 4.7] and assign it 
  print np_arr[1] 
- try printing np_arr[1:-4] to see what the equals?
- Create a 2-D array from the following list and assign it 
  [[2, 3.2, 5.5, -6.4, -2.2, 2.4], 
  [1, 22, 4, 0.1, 5.3, -9], 
  [3, 1, 2.1, 21, 1.1, -2]]

- try printing the following
  a[:, 3], 
  a[1:4, 0:4], 
  a[1:, 2] 

In [30]:
import numpy as np
np_arr = np.array([2,5.5, -7.2, 3.5, 2.7, 4.7])

In [31]:
np_arr

array([ 2. ,  5.5, -7.2,  3.5,  2.7,  4.7])

In [32]:
np_arr[1]

5.5

In [33]:
np_arr[1:4]

array([ 5.5, -7.2,  3.5])

In [34]:
np_arr = np.array([[2, 3.2, 5.5, -6.4, -2.2, 2.4],
                [1, 22, 4, 0.1, 5.3, -9],
                [3, 1, 2.1, 21, 1.1, -2]])

In [35]:
np_arr

array([[ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4],
       [ 1. , 22. ,  4. ,  0.1,  5.3, -9. ],
       [ 3. ,  1. ,  2.1, 21. ,  1.1, -2. ]])

In [36]:
np_arr[:,3]

array([-6.4,  0.1, 21. ])

In [37]:
np_arr[1:2, 3:4]

array([[0.1]])

#### POPCORN QUIZ
Write a Python program to create a 2d array with 1 on the border and 0 inside.
- Sample Output

 Original array:     
 
    [[ 1.  1.  1.  1.  1.]                                                  
 [ 1.  1.  1.  1.  1.]                                                  
 [ 1.  1.  1.  1.  1.]                                                  
 [ 1.  1.  1.  1.  1.]                                                  
 [ 1.  1.  1.  1.  1.]]  
 
 result in below:
 
    [[ 1.  1.  1.  1.  1.]                                                  
 [ 1.  0.  0.  1.  1.]                                                  
 [ 1.  0.  0.  1.  1.]                                                  
 [ 1.  0.  0.  1.  1.]                                                  
 [ 1.  1.  1.  1.  1.]]

In [38]:
import numpy as np  # itp11704
np_arr = np.ones((5,5))
print(np_arr)
# write your answer in here
np_arr[1:4, 1:3] = np.zeros((3,2))
print(np_arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 1. 1.]
 [1. 0. 0. 1. 1.]
 [1. 0. 0. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### Practice 3
- Create a 2-D array of shape (2, 4) containing two lists (range(4), range(10, 14)) and assign it
- Check the shape, the size,n the maximum and minimum of the array 

In [39]:
import numpy as np
np_arr=np.array([range(4),range(10,14)])
print(np_arr.shape)
print(np_arr.size)
print(np_arr.max())
print(np_arr.min())

(2, 4)
8
13
0


- Contiunue to use the array as defined above. 
- print the array re-shaped to (2,2,2)
- print the array transposed
- print the array flattened to a single dimension

In [40]:
np.reshape(np_arr,(4,2))
print(np_arr)
np.transpose(np_arr)
np.ravel(np_arr)

[[ 0  1  2  3]
 [10 11 12 13]]


array([ 0,  1,  2,  3, 10, 11, 12, 13])

## 4. Mathematical Operations and Array Calculations 

NumPy n-dimensional arrays makes it extremely easy to perform mathematical operations on it.
- Mathematical operations with arrays
- Mathematical operations mixing scalars and arrays
- Comparison operators and Boolean operations on arrays
- Broadcasting

In [41]:
py_arr = [1,2,3] * 2

In [42]:
np_arr = np.array([1,2,3]) * 2 

In [43]:
py_arr

[1, 2, 3, 1, 2, 3]

In [44]:
np_arr

array([2, 4, 6])

multi dimensional mathematical operations

In [45]:
np_arr = np.ones((5,2)) * 10

In [46]:
np_arr

array([[10., 10.],
       [10., 10.],
       [10., 10.],
       [10., 10.],
       [10., 10.]])

#### Practice 4
- Create a 2-D array of shape (2, 4) containing two lists (range(4), range(10, 14)) and assign it to the   
  variable "a" 
- Create an array from a list [2, -1, 1, 0] and assign it to the variable "b"
- Multiply array "a" by "b" and view the result. Do you understand how NumPy has used its broadcasting feature
  to do the calculation even though the arrays are different shapes?
- Multiply array "b" by 100 and assign the result to the variable "b1".
- Multiply array "b" by 100.0 and assign the result to the variable "b2".
- Print the arrays "b1" and "b2".
- Print "b1 == b2". Are they the same?
- Why do they display differently? Interrogate the typecode of each array to find out why.

In [47]:
import numpy as np

In [48]:
a = np.array([range(4), range(10,14)])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [49]:
b = np.array([2,-1,1,0])
b

array([ 2, -1,  1,  0])

In [50]:
# a*b
print(a*b)

[[  0  -1   2   0]
 [ 20 -11  12   0]]


In [51]:
# b1
b1 = 100*b
b1

array([ 200, -100,  100,    0])

In [52]:
#b2
b2 = 100.0*b
b2

array([ 200., -100.,  100.,    0.])

In [53]:
#print 
print(b1 == b2)

[ True  True  True  True]


### Broadcasting 
Broadcasting is simply a set of rules for applying binary ufuncs (e.g., addition, subtraction, multiplication, etc.) on arrays of different sizes.


In [54]:
import numpy as np

In [55]:
a = np.array([0,1,2])
b = np.array([5,5,5])

In [56]:
a+b

array([5, 6, 7])

Broadcasting allows these types of binary operations to be performed on arrays of different sizes–for example,
you can just as easily add a scalar (think of it as a zero-dimensional array) to an array:

In [57]:
a+5

array([5, 6, 7])



You can think of this as an operation that stretches or duplicates the value 5 into the array [5, 5, 5], and adds the results. The advantage of NumPy's broadcasting is that this duplication of values does not actually take place, but it is a useful mental model as we think about broadcasting.

You can similarly extend this to arrays of higher dimension. Observe the result when we add a one-dimensional array to a two-dimensional array:


In [58]:
c = np.ones((3,3))

In [59]:
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [60]:
c + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])



Here the one-dimensional array a is stretched, or broadcast across the second dimension in order to match the shape of j.

While these examples are relatively easy to understand, more complicated cases can involve broadcasting of both arrays. Consider the following example:


In [61]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

In [62]:
print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [63]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

Just as before we stretched or broadcasted one value to match the shape of the other, here we've stretched both a and b to match a common shape, and the result is a two-dimensional array! The geometry of these examples is visualized in the following figure 

<script src="https://npmcdn.com/jupyter-js-widgets@~1.2.0/dist/embed.js"></script><img src='https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png'><script type="application/vnd.jupyter-embedded-widgets">{}</script>


The light boxes represent the broadcasted values: again, this extra memory is not actually allocated in the course of the operation, but it can be useful conceptually to imagine that it is.

### Rules of Broadcasting

Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:

    1.Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
    2. Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
    3. Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [64]:
a = np.ones((2,3))
print(a)
b = np.arange(3)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]


In [65]:
s1 = a.shape
print(s1)
s2 = b.shape
print(s2)

(2, 3)
(3,)


Let's consider an operation on these two arrays. The shape of the arrays are

a.shape = (2, 3)
b.shape = (3,)
We see by rule 1 that the array a has fewer dimensions, so we pad it on the left with ones:

a.shape -> (2, 3)
b.shape -> (1, 3)
By rule 2, we now see that the first dimension disagrees, so we stretch this dimension to match:

a.shape -> (2, 3)
b.shape -> (2, 3)
The shapes match, and we see that the final shape will be (2, 3):

In [66]:
s = a+b
print(s)
s.shape

[[1. 2. 3.]
 [1. 2. 3.]]


(2, 3)

In [67]:
a = np.arange(3).reshape((3,1))
b = np.arange(3)

Again, we'll start by writing out the shape of the arrays:

a.shape = (3, 1)
b.shape = (3,)
Rule 1 says we must pad the shape of b with ones:

a.shape -> (3, 1)
b.shape -> (1, 3)
And rule 2 tells us that we upgrade each of these ones to match the corresponding size of the other array:

a.shape -> (3, 3)
b.shape -> (3, 3)
Because the result matches, these shapes are compatible. We can see this here:

In [68]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [69]:
a = np.ones((3,2))
print(a)
b = np.arange(3)
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 1 2]


This is just a slightly different situation than in the first example: the matrix M is transposed. How does this affect the calculation? The shape of the arrays are

M.shape = (3, 2)
a.shape = (3,)
Again, rule 1 tells us that we must pad the shape of a with ones:

M.shape -> (3, 2)
a.shape -> (1, 3)
By rule 2, the first dimension of a is stretched to match that of M:

M.shape -> (3, 2)
a.shape -> (3, 3)
Now we hit rule 3–the final shapes do not match, so these two arrays are incompatible, as we can observe by attempting this operation:

In [70]:
a + b

ValueError: ignored

Note the potential confusion here: you could imagine making a and a compatible by, say, padding b's shape with ones on the right rather than the left. But this is not how the broadcasting rules work! That sort of flexibility might be useful in some cases, but it would lead to potential areas of ambiguity. If right-side padding is what you'd like, you can do this explicitly by reshaping the array 

In [71]:
c= b[:, np.newaxis]

In [72]:
a + c

array([[1., 1.],
       [2., 2.],
       [3., 3.]])

Thanks for your attention!!! 