## AIP II Lab_07  Quiz (Total : 50 pts)

ITP11704 Section :: Nov. 02

Your Student_id :                    , Your name: 
* If your section is different, write your section in below
Your section : 

These quizzes will cover NumPy in detail. NumPy(short for Numerical Python) provides an efficient interface to store and operate on dense buffers. 

## np.array  :: Problem 01, Problem 02
The most common way to create an array is to construct one form a python list

Passing a list of **scalars** produces a 1-dimensional array.

In [19]:
import numpy as np

In [20]:
np.array([1,2,3])

array([1, 2, 3])

Passing a list of lists produces a 2-dimensional array

In [4]:
np.array([[1,2], [2,3]])

array([[1, 2],
       [2, 3]])

### Problem 01(2 pts)

Create a 1-dimensional array using np.array containing [1,2,3,4]

In [6]:
# Write your answer below

# output : array([1,2,3,4])

array([1, 2, 3, 4])

### Problem 02(2 pts)

Create a 2-dimensional array using np.array with two rows containing [1, 2, 3] and [4, 5, 6].

In [9]:
# Write your answer below


# output : array([[1, 2, 3],
#                 [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

--------------------------------------------------------------------------------------------------------------------------------

## np.arange :: Problem 03, Problem 04

### Problem 03(2 pts)

Construct an array containing values from 0 to 9, exclusive, in ascending order.

In [3]:
# Write your answer below


# output : array([0, 1, 2, 3, 4, 5, 6, 7, 8])
assert np.array_equal(np_arr, np.array([0, 1, 2, 3, 4, 5, 6, 7, 8]) ), "Wrong Answer"
np_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### Problem 04(2 pts)

Construct an array containing all the integers between 1 and 10 exclusive, in descending order.

In [5]:
# Write your answer below


# output : array([9,  8,  7,  6,  5,  4,  3,  2, 1])
assert np.array_equal(np_arr,np.array([9,  8,  7,  6,  5,  4,  3,  2,  1])), "Wrong Answer"
np_arr

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

--------------------------------------------------------------------------------------------------------------------------------

## Reshapeing Arrays  :: Problem 05, Problem 06

The most general way to reshape an array is to use the .reshape method of ndarray. .reshape accepts a tuple of new dimensions and

In [17]:
import numpy as np
np_arr = np.arange(12)
np_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Problem 05(2 pts) 

Reshape np_arr to an array with **four rows and three columns**:

In [22]:
# Write your answer below
np_arr = np.arange(12)
np_arr = ___________________  # Writer your answer in here

assert np.array_equal(np_arr,np.array([[ 0,  1,  2],
                                       [ 3,  4,  5],
                                       [ 6,  7,  8],
                                       [ 9, 10, 11]])), "Wrong Answer"
np_arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### Problem 06(2 pts) 

Reshape np_arr into an array of shape (2, 2, 3)

In [25]:
# Write your answer below

np_arr = ___________________   # Writer your answer in here
assert np.array_equal(np_arr,np.array([[[ 0, 1, 2],
                                        [ 3, 4, 5]],
                                       
                                       [[ 6, 7, 8],
                                        [ 9, 10, 11]]])), "Wrong Answer"
np_arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

--------------------------------------------------------------------------------------------------------------------------------

### Transpose


A common pattern, especially when doing linear algebra with 2D arrays, is to need to "rotate" an array by 90 degrees. This operation is commonly known as "transposing" the array.


### Problem 07(3 pts)

Use the .transpose() method to convert data from a 2 x 4 array into a 4 x 2 array

In [26]:
# Write your answer below
# Make an array using by .arange() and .reshape()
np_arr = ___________________________  
assert np.array_equal(np_arr,np.array([[0, 1, 2, 3],
                                       [4, 5, 6, 7]])), "Wrong Answer"
np_arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [18]:
# Write your answer below
# Adjust transpose() in this shell
np_arr = ______________________

assert np.array_equal(np_arr,np.array([[0, 4],
                                       [1, 5],
                                       [2, 6],
                                       [3, 7]])), "Wrong Answer"
np_arr

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

--------------------------------------------------------------------------------------------------------------------------------

### Problem 08.  indexing (5 pts)

In [5]:
import numpy as np
np_arr = np.arange(12).reshape((3,4))
np_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

How to get the output from the above NumPy array?

In [9]:
# Write your answer below, just use indexing and do not use loops!
import numpy as np
np_arr = np.arange(12).reshape((3,4))
np_arr = ___________________

assert np.array_equal(np_arr,np.array([[10, 9, 11]])), "Wrong Answer"
np_arr

array([[10,  9, 11]])

### Problem 09(10 pts). 
Write a Python program to create a 2d array as shown in the result array. And you must follow the rules below.
- Rule 1: You should use multiple and indexing based on the sample array.
- Rule 2: You should create the result array within 4 lines of code.
- Rule 3: Numbers 2, 3, and 4 are not allowed for the index to multiply.



In [13]:
import numpy as np
np_arr = np.ones((6,6))
print("This is the original array.")
print(np_arr)

This is the original array.
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [12]:
import numpy as np
np_arr = np.ones((6,6))
print("My answer is below: ")
# Write your answer below






print(np_arr)
# My answer is below: 
#[[2. 2. 2. 2. 2. 2.]
# [3. 0. 0. 0. 0. 3.]
# [3. 0. 0. 0. 0. 3.]
# [3. 0. 0. 0. 0. 3.]
# [3. 0. 0. 0. 0. 3.]
# [2. 2. 2. 2. 2. 2.]]

My answer is below: 
[[2. 2. 2. 2. 2. 2.]
 [3. 0. 0. 0. 0. 3.]
 [3. 0. 0. 0. 0. 3.]
 [3. 0. 0. 0. 0. 3.]
 [3. 0. 0. 0. 0. 3.]
 [2. 2. 2. 2. 2. 2.]]


### Problem 10(20 pts). 
- Make a function that take two 2D arrays A and B as input parameters and returns a result C that matrix multiplication of two input.(See figure.3)
- **Do not use built-in numpy function like np.dot(But you can use it to validate your function.)** and use default python function sum()                                               
(Hint: Use the np.shape to check the input array's shape)

In [7]:
import numpy as np
A = np.array([[2,3,1],[1,4,2],[3,1,1],[1,2,4]])
B = np.array([[3,2,6,3],[2,3,1,5],[5,1,2,3]])
print(A)
print(B)

[[2 3 1]
 [1 4 2]
 [3 1 1]
 [1 2 4]]
[[3 2 6 3]
 [2 3 1 5]
 [5 1 2 3]]


In [1]:
from IPython.core.display import Image 
from IPython.core.display import HTML

In [2]:
Image(url='https://s3-ap-southeast-1.amazonaws.com/learn-ap-southeast-1-prod-fleet02-xythos/5a8801a04ee83/134674?response-content-disposition=inline%3B%20filename%2A%3DUTF-8%27%27index2.png&response-content-type=image%2Fpng&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20181101T081705Z&X-Amz-SignedHeaders=host&X-Amz-Expires=21599&X-Amz-Credential=AKIAJDDBGKVKR5QVHNHA%2F20181101%2Fap-southeast-1%2Fs3%2Faws4_request&X-Amz-Signature=a72659df9b0e6c7050be14c4011ac03ec230cba6ae68b731233ed60f1f36e7c6')


In [8]:
def matrixMultiple(A,B):
    C = np.empty((A.shape[0],B.shape[1]),dtype = np.int)
    # Write your answer below


    
    
    
    
    return C
print(matrixMultiple(A,B))
assert (matrixMultiple(A,B) == np.dot(A,B)).all()
#[[17 14 17 24]
# [21 16 14 29]
# [16 10 21 17]
# [27 12 16 25]]


[[17 14 17 24]
 [21 16 14 29]
 [16 10 21 17]
 [27 12 16 25]]
