In [ ]:
import tensorflow as tf

In [ ]:
x = tf.placeholder(tf.float32)

In [ ]:
y = tf.placeholder(tf.float32)

In [ ]:
z = tf.multiply(x,y)
with tf.Session() as sess:
    print(sess.run(z, feed_dict={x: [[3., 3.], [3., 3.]], y: [[5., 5.], [5., 5.]]}))

In [ ]:
import tensorflow as tf

x = tf.placeholder(tf.float32, shape=(2, 2))
y = tf.placeholder(tf.float32, shape=(2, 2))
z = tf.multiply(x, y)

with tf.Session() as sess:
    print(sess.run(z, feed_dict={x: [[3., 3.], [3., 3.]], y: [[5., 5.], [5., 5.]]}))

In [ ]:
import tensorflow as tf

with tf.Session() as sess:
    with tf.device("/cpu:0"):
#with tf.device("/gpu:0"):
        x = tf.placeholder(tf.float32)
        y = tf.placeholder(tf.float32)
        z = tf.multiply(x, y)
        print(sess.run(z, feed_dict={x: [[3., 3.], [3., 3.]], y: [[5., 5.], [5., 5.]]}))



In [ ]:

import tensorflow as tf

sess = tf.InteractiveSession()

x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = tf.multiply(x, y)

print(z.eval(feed_dict={x: [[3., 3.], [3., 3.]], y: [[5., 5.], [5., 5.]] }))

sess.close()

In [ ]:
import tensorflow as tf
sess = tf.InteractiveSession()

In [ ]:

x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = tf.multiply(x, y)

print(z.eval(feed_dict={x: [[3., 3.], [3., 3.]], y: [[5., 5.], [5., 5.]] }))

sess.close()

In [ ]:
import tensorflow as tf
tf.InteractiveSession()
a = tf.zeros((2,2)); b = tf.ones((2,2))
tf.reduce_sum(b, reduction_indices = 1).eval()


In [ ]:
a.get_shape()

In [ ]:
import numpy as np
a = np.zeros((2,2))

In [ ]:
ta = tf.zeros((2,2))

In [ ]:
print(a)

In [ ]:
print(ta)

In [ ]:
print(ta.eval())

In [ ]:
a = tf.constant(5.0)
b = tf.constant(6.0)
c = a*b

In [ ]:
with tf.Session() as sess:
    print(sess.run(c))
    print(c.eval())

In [ ]:
w1 = tf.ones((2,2))
w2 = tf.Variable(tf.zeros((2,2)), name="weights")
with tf.Session() as sess:
    print(sess.run(w1))
    sess.run(tf.initialize_all_variables())
    print(sess.run(w2))

In [ ]:
W = tf.Variable(tf.zeros((2,2)), name="weights")
R = tf.Variable(tf.random_normal((2,2)), name="random_weights")

In [ ]:
with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    print(sess.run(W))
    print(sess.run(R))

In [ ]:
state = tf.Variable(0, name="counter")
new_value = tf.add(state, tf.constant(1))
update = tf.assign(state, new_value)

In [ ]:
with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    print(sess.run(state))
    for _ in range(3):
        sess.run(update)
        print(sess.run(state))

In [ ]:
input1 = tf.constant(3.0)
input2 = tf.constant(2.0)
input3 = tf.constant(5.0)
intermd = tf.add(input2, input3)
mul = tf.multiply(input1, intermd)

In [ ]:
with tf.Session() as sess:
    result  = sess.run([mul, intermd])
    print(result)

In [ ]:
a = np.zeros((3,3))

In [ ]:
ta = tf.convert_to_tensor(a)

In [ ]:
with tf.Session() as sess:
    print(sess.run(ta))

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
sns.set()
sns.set_style('whitegrid')
sns.set_color_codes()

mpl.rc('font', family='nanumgothic')
mpl.rc('axes', unicode_minus=False)


In [ ]:
import numpy as np
import matplotlib.pyplot as mpl
import seaborn
# Define input data
X_data = np.arange(100, step=.1)
y_data = X_data + 20 * np.sin(X_data/10)
# Plot input data
plt.scatter(X_data, y_data)

In [ ]:
# Define data size and batch size
n_samples = 1000
batch_size = 100
# Tensorflow is finicky about shapes, so resize
X_data = np.reshape(X_data, (n_samples,1))
y_data = np.reshape(y_data, (n_samples,1))
# Define placeholders for input
X = tf.placeholder(tf.float32, shape=(batch_size, 1))
y = tf.placeholder(tf.float32, shape=(batch_size, 1))

In [ ]:
with tf.variable_scope("linear-regression"):
    W = tf.get_variable("weights", (1, 1), initializer=tf.random_normal_initializer())
    b = tf.get_variable("bias", (1,), initializer=tf.constant_initializer(0.0))
    y_pred = tf.matmul(X, W) + b
    loss = tf.reduce_sum((y - y_pred)**2/n_samples)

In [ ]:
def run_training():
  """Train MNIST for a number of steps."""
  # Get the sets of images and labels for training, validation, and
  # test on MNIST.
  data_sets = input_data.read_data_sets(FLAGS.train_dir, FLAGS.fake_data)

In [ ]:
# Tell TensorFlow that the model will be built into the default Graph.
with tf.Graph().as_default():
 # Generate placeholders for the images and labels.
    images_placeholder, labels_placeholder = placeholder_inputs(FLAGS.batch_size)



In [ ]:
import tensorflow as tf


# MNIST 데이터 불러오기
from tensorflow.examples.tutorials.mnist import input_data
mnistData = input_data.read_data_sets("MNIST_data/", one_hot=True)

# 28*28 image data features
x = tf.placeholder(tf.float32, [None, 784])

# theta
W = tf.Variable(tf.zeros([784,10]))

# bias term
b = tf.Variable(tf.zeros([10]))

# h(x) using softmax
y = tf.nn.softmax(tf.matmul(x, W) + b)

# prediction values
y_ = tf.placeholder(tf.float32, [None, 10])

# Cost function
cross_entropy = tf.reduce_mean(- tf.reduce_sum(y_ * tf.log(y), reduction_indices=[1]))

# Gradient descent
train_step = tf.train.GradientDescentOptimizer(0.5).minimize(cross_entropy)

# 모든 변수 초기화

init = tf.initialize_all_variables()

# Session 생성

sess = tf.Session()

sess.run(init)

# training
for i in range(1000):
    batch_xs, batch_ys = mnistData.train.next_batch(100)
    sess.run(train_step, feed_dict={x: batch_xs, y_:batch_ys})

# training 결과 확인

correct_prediction = tf.equal(tf.argmax(y,1), tf.argmax(y_,1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
print(sess.run(accuracy, feed_dict={x: mnistData.test.images, y_: mnistData.test.labels}))




In [ ]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnistData = input_data.read_data_sets('MNIST_data', one_hot=True)

sess = tf.InteractiveSession()

x = tf.placeholder(tf.float32, shape=[None, 784])
y_ = tf.placeholder(tf.float32, shape=[None, 10])

def weight_variable(shape):
    initial = tf.truncated_normal(shape, stddev=0.1)
    return tf.Variable(initial)

def bias_variable(shape):
    initial = tf.constant(0.1, shape=shape)
    return tf.Variable(initial)

def conv2d(x,W):
    return tf.nn.conv2d(x, W, strides=[1,1,1,1], padding='SAME')

def max_pool_2x2(x):
    return tf.nn.max_pool(x, ksize=[1,2,2,1], strides=[1,2,2,1], padding='SAME')

# Layer 1, 5x5 patch, 32 output
W_conv1 = weight_variable([5,5,1,32])
b_conv1 = bias_variable([32])

x_image = tf.reshape(x, [-1,28,28,1])

h_conv1 = tf.nn.relu(conv2d(x_image, W_conv1) + b_conv1)
h_pool1 = max_pool_2x2(h_conv1)


# Layer 2, 5x5 patch, 64 output
W_conv2 = weight_variable([5,5,32,64])
b_conv2 = bias_variable([64])

h_conv2 = tf.nn.relu(conv2d(h_pool1, W_conv2) + b_conv2)
h_pool2 = max_pool_2x2(h_conv2)

# Layer 3, 7x7 image size, 1024 output
W_fc1 = weight_variable([7*7*64, 1024])
b_fc1 = bias_variable([1024])

h_pool2_flat = tf.reshape(h_pool2, [-1, 7*7*64])
h_fc1 = tf.nn.relu(tf.matmul(h_pool2_flat, W_fc1) + b_fc1)

# dropout
keep_prob = tf.placeholder(tf.float32)
h_fc1_drop = tf.nn.dropout(h_fc1, keep_prob)

# final output
W_fc2 = weight_variable([1024, 10])
b_fc2 = bias_variable([10])

y_conv=tf.nn.softmax(tf.matmul(h_fc1_drop, W_fc2) + b_fc2)


# training
cross_entropy = tf.reduce_mean(- tf.reduce_sum(y_ * tf.log(y_conv), reduction_indices=[1]))
train_step = tf.train.AdamOptimizer(1e-4).minimize(cross_entropy)
correct_prediction = tf.equal(tf.argmax(y_conv,1), tf.argmax(y_,1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
sess.run(tf.initialize_all_variables())

for i in range(20000):
    batch = mnistData.train.next_batch(50)
    if i%100 == 0:
        train_accuracy = accuracy.eval(feed_dict={x:batch[0], y_:batch[1], keep_prob: 1.0})
        print("step %d, training accuracy %g"%(i, train_accuracy))
    train_step.run(feed_dict={x: batch[0], y_:batch[1], keep_prob: 0.5})

print("test accuracy %g"%accuracy.eval(feed_dict={x: mnistData.test.images, y_: mnistData.test.labels, keep_prob: 1.0}))



In [3]:
import tensorflow as tf

In [19]:
x = tf.constant(3)
print(x)
sess = tf.Session()
result = sess.run(x)
print(result)

Tensor("Const_13:0", shape=(), dtype=int32)
3


In [20]:
import tensorflow as tf
x = tf.constant(3.)
print(x)
sess = tf.Session()
result  = sess.run(x)
print(result)

Tensor("Const_14:0", shape=(), dtype=float32)
3.0


In [21]:
import tensorflow as tf
x = tf.constant([3.,3.])
print(x)

Tensor("Const_15:0", shape=(2,), dtype=float32)


In [22]:
sess = tf.Session()
result = sess.run(x)
print(result)

[3. 3.]


In [24]:
import tensorflow as tf

x = tf.constant([[3.,3.],[5.,5.]])
print(x)

sess = tf.Session()
result = sess.run(x)
print(result)





Tensor("Const_16:0", shape=(2, 2), dtype=float32)
[[3. 3.]
 [5. 5.]]


In [25]:

import tensorflow as tf

x = tf.constant([[3.,3.],[5.,5.],[7.,7.]])
print(x)

sess = tf.Session()
result = sess.run(x)
print(result)





Tensor("Const_17:0", shape=(3, 2), dtype=float32)
[[3. 3.]
 [5. 5.]
 [7. 7.]]


In [26]:
import tensorflow as tf

x = tf.constant( [ [[3.,3.],[5.,5.],[7.,7.]],[[2.,2.],[4.,4.],[6.,6.]] ] )
print(x)

sess = tf.Session()
result = sess.run(x)
print(result)

Tensor("Const_18:0", shape=(2, 3, 2), dtype=float32)
[[[3. 3.]
  [5. 5.]
  [7. 7.]]

 [[2. 2.]
  [4. 4.]
  [6. 6.]]]


In [52]:
import tensorflow as tf

x = tf.Variable(tf.random_normal([784, 200], stddev=0.35))
y = tf.Variable(x.initialized_value() + 3.)

init_op = tf.initialize_all_variables()

saver = tf.train.Saver()

sess = tf.Session()
sess.run(init_op)
save_path = saver.save(sess, "/tmp/model.ckpt")
print(sess.run(x))





[[ 0.12436315 -0.16061217  0.27105504 ... -0.18545213 -0.11371412
  -0.03499937]
 [-0.05456297  0.12508093  0.0659489  ...  0.41405958 -0.02302197
   0.13249035]
 [ 0.5827049   0.35431468  0.2517694  ... -0.41139293 -0.17084135
   0.34003168]
 ...
 [ 0.2013187   0.0063904  -0.11036041 ... -0.3338372   0.92396086
  -0.08437262]
 [-0.21696512  0.99820966 -0.37269706 ... -0.39824355  0.25640005
  -0.10631395]
 [-0.02337295 -0.17290816  0.4470973  ... -0.16431603  0.40587804
   0.00428574]]


In [50]:

import tensorflow as tf

x = tf.Variable(tf.random_normal([784, 200], stddev=0.35))
y = tf.Variable(x.initialized_value() + 3.)

init_op = tf.initialize_all_variables()

saver = tf.train.Saver()

sess = tf.Session()
sess.run(init_op)
saver.restore(sess, "/tmp/model.ckpt")
print(sess.run(x))





INFO:tensorflow:Restoring parameters from /tmp/model.ckpt


NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key Variable_46 not found in checkpoint
	 [[node save_23/RestoreV2 (defined at <ipython-input-50-59b267920c3a>:9)  = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_23/Const_0_0, save_23/RestoreV2/tensor_names, save_23/RestoreV2/shape_and_slices)]]
	 [[{{node save_23/RestoreV2/_15}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_19_save_23/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'save_23/RestoreV2', defined at:
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 497, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.5/dist-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 345, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1312, in _run_once
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.5/dist-packages/tornado/platform/asyncio.py", line 122, in _handle_events
    handler_func(fileobj, events)
  File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2901, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-50-59b267920c3a>", line 9, in <module>
    saver = tf.train.Saver()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1102, in __init__
    self.build()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1114, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1151, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 795, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 406, in _AddRestoreOps
    restore_sequentially)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 862, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 1466, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key Variable_46 not found in checkpoint
	 [[node save_23/RestoreV2 (defined at <ipython-input-50-59b267920c3a>:9)  = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_23/Const_0_0, save_23/RestoreV2/tensor_names, save_23/RestoreV2/shape_and_slices)]]
	 [[{{node save_23/RestoreV2/_15}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_19_save_23/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
